[book]
title = "Fungi Protocol"
language = "en"
src = "src"

[preprocessor.graphviz]
command = "mdbook-graphviz"

[preprocessor.mermaid]
command = "python3 contrib/mermaid_ssr.py"

[preprocessor.katex]
command = "mdbook-katex"
